<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require __DIR__.'/sarathi.php';
require_once __DIR__.'/../../controllers/deliverySafety.php';
use function Maakit\Api\{company_apply,company_configure,company_booking,company_list,company_orders,company_key,company_tick,company_accept,company_progress,company_tracking,company_view_proof,company_codes,company_cancel,order_safety_codes,company_proof};
$f=fixture($db);$owner=$f['a'];$stranger=person($db);$admin=person($db,'ADMIN');$permission=Maakit\Api\query($db,"SELECT id FROM mk_permissions WHERE code='DISPATCH_WRITE'")->fetchColumn();add($db,'mk_user_permissions',['user_id'=>$admin['user_id'],'permission_id'=>$permission]);$admin=Maakit\Api\live_identity($db,$admin['claims']);
$c=company_apply($db,$owner,['name'=>'Test company','phone'=>'9876543210']);check(company_apply($db,$owner,['name'=>'Same company','phone'=>'9876543210'])['id']===$c['id'],'company application is idempotent');
$address=['name'=>'Test recipient','phone'=>'9876543210','address'=>'Test address','latitude'=>25.0,'longitude'=>82.0];$body=['company_id'=>$c['id'],'store_id'=>$f['store'],'reference'=>Maakit\Api\uuid4(),'fleet'=>'SHARED','pickup'=>$address,'stops'=>[$address,$address],'contact_consent'=>true,'emergency_contacts'=>[['name'=>'Family','phone'=>'9876543210']]];
rejected(fn()=>company_booking($db,$owner,$body),'COMPANY_NOT_ACTIVE');rejected(fn()=>company_configure($db,$owner,[]),'FORBIDDEN');
company_configure($db,$admin,['company_id'=>$c['id'],'store_id'=>$f['store'],'state'=>'ACTIVE','base_minor'=>1000,'drop_minor'=>2000,'radius_m'=>5000]);
rejected(fn()=>company_orders($db,$stranger,$c['id']),'NOT_FOUND');$bad=$body;$bad['stops'][0]['latitude']=26.0;rejected(fn()=>company_booking($db,$owner,$bad),'OUTSIDE_SERVICE_AREA');$bad=$body;$bad['contact_consent']=false;rejected(fn()=>company_booking($db,$owner,$bad),'CONSENT_REQUIRED');
$body['fee_minor']=1;$quote=company_booking($db,$owner,$body,true);check($quote['fee_minor']===5000,'trusted company area tariff ignores caller fee');$b=company_booking($db,$owner,$body);check(company_booking($db,$owner,$body)['replayed'],'company booking replay creates no duplicate');$bad=$body;$bad['stops'][0]['address']='Different';rejected(fn()=>company_booking($db,$owner,$bad),'IDEMPOTENCY_CONFLICT');
$key=company_key($db,$owner,['company_id'=>$c['id']]);check(Maakit\Api\query($db,'SELECT token_hash FROM mk_company_keys WHERE id=?',[$key['key_id']])->fetchColumn()===hash('sha256',$key['token']),'company API key stored only as hash');$keyAuth=['company_key'=>$key['key_id'],'company_id'=>$c['id'],'user_id'=>$owner['user_id'],'roles'=>[],'permissions'=>[]];check(company_orders($db,$keyAuth,$c['id'])['deliveries'][0]['id']===$b['id'],'company key scoped to its company');rejected(fn()=>company_orders($db,$keyAuth,Maakit\Api\uuid4()),'NOT_FOUND');company_key($db,$owner,['company_id'=>$c['id'],'revoke_id'=>$key['key_id']]);rejected(fn()=>company_orders($db,$keyAuth,$c['id']),'NOT_FOUND');
$r=rider($db,$f,false);company_tick($db);check(company_list($db,$stranger)['companies']===[],'other customer cannot list company');$offer=Maakit\Api\company_partner($db,$r['auth']);check(count($offer)===1&&!isset($offer[0]['emergency_contacts'])&&!isset($offer[0]['pickup']),'offer hides customer contact and OTP');
$otherRider=rider($db,$f,false);rejected(fn()=>company_accept($db,$otherRider['auth'],['delivery_id'=>$b['id']]),'NOT_FOUND');company_accept($db,$r['auth'],['delivery_id'=>$b['id']]);check(company_accept($db,$r['auth'],['delivery_id'=>$b['id']])['replayed'],'company acceptance is idempotent');
check(!str_contains(json_encode(Maakit\Api\company_partner($db,$r['auth'])),'pickup_otp'),'assigned partner never receives OTP');
rejected(fn()=>company_progress($db,$r['auth'],['delivery_id'=>$b['id'],'operation'=>'drop','stop'=>1,'otp'=>$b['drop_otps'][0]['otp']]),'INVALID_TRANSITION');
rejected(fn()=>company_progress($db,$r['auth'],['delivery_id'=>$b['id'],'operation'=>'pickup','otp'=>'000000']),'INVALID_OTP');check((int)Maakit\Api\query($db,'SELECT pickup_attempts FROM mk_company_deliveries WHERE id=?',[$b['id']])->fetchColumn()===1,'bad OTP attempts persist despite rejected request');
company_progress($db,$r['auth'],['delivery_id'=>$b['id'],'operation'=>'pickup','otp'=>$b['pickup_otp']]);
rejected(fn()=>company_progress($db,$r['auth'],['delivery_id'=>$b['id'],'operation'=>'drop','stop'=>2,'otp'=>$b['drop_otps'][1]['otp']]),'INVALID_TRANSITION');rejected(fn()=>company_progress($db,$r['auth'],['delivery_id'=>$b['id'],'operation'=>'drop','stop'=>1,'otp'=>$b['drop_otps'][0]['otp']]),'PROOF_REQUIRED');
$image='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1sAAAAASUVORK5CYII=';rejected(fn()=>company_proof(base64_encode('<svg></svg>')),'PROOF_REQUIRED');
company_progress($db,$r['auth'],['delivery_id'=>$b['id'],'operation'=>'drop','stop'=>1,'otp'=>$b['drop_otps'][0]['otp'],'proof_base64'=>$image]);check(company_progress($db,$r['auth'],['delivery_id'=>$b['id'],'operation'=>'drop','stop'=>1])['replayed'],'repeat stop completion does not advance twice');
rejected(fn()=>company_view_proof($db,$stranger,$c['id'],$b['id'],1),'NOT_FOUND');check(company_view_proof($db,$owner,$c['id'],$b['id'],1)['mime']==='image/png','company proof kept behind ownership checks');
$token=substr($b['tracking_url'],strrpos($b['tracking_url'],'#')+1);check(company_tracking($db,$token)['state']==='PICKED_UP','private tracking link reads state');rejected(fn()=>company_tracking($db,str_repeat('a',64)),'NOT_FOUND');
company_progress($db,$r['auth'],['delivery_id'=>$b['id'],'operation'=>'drop','stop'=>2,'otp'=>$b['drop_otps'][1]['otp'],'proof_base64'=>$image]);check(company_tracking($db,$token)['location']===null,'company tracking stops after delivery');check((int)company_orders($db,$owner,$c['id'])['summary']['delivered_fee_minor']===5000,'company fee ledger records only completed delivery charges');
$body['reference']=Maakit\Api\uuid4();$new=company_booking($db,$owner,$body);$codes=company_codes($db,$owner,['company_id'=>$c['id'],'delivery_id'=>$new['id']]);rejected(fn()=>company_tracking($db,substr($new['tracking_url'],strrpos($new['tracking_url'],'#')+1)),'NOT_FOUND');check(isset($codes['pickup_otp']),'lost creation response can safely rotate codes');company_cancel($db,$owner,['company_id'=>$c['id'],'delivery_id'=>$new['id']]);check(Maakit\Api\query($db,'SELECT state FROM mk_company_deliveries WHERE id=?',[$new['id']])->fetchColumn()==='CANCELLED','company cancellation ends unaccepted request');
// An occupied rider cannot receive a Maakit offer from a second queue.
Maakit\Api\query($db,"UPDATE mk_rider_duty SET available_until=UTC_TIMESTAMP(6)");Maakit\Api\rider_duty($db,$r['auth'],'online');$body['reference']=Maakit\Api\uuid4();$busy=company_booking($db,$owner,$body);company_tick($db);company_accept($db,$r['auth'],['delivery_id'=>$busy['id']]);
$mf=ready_order($db);add($db,'mk_rider_zones',['rider_id'=>$r['id'],'store_id'=>$mf['store'],'fulfillment_type'=>'HYPERLOCAL','active'=>1]);Maakit\Api\dispatch_tick($db,$noNetwork);check(!Maakit\Api\query($db,"SELECT id FROM mk_dispatch_attempts WHERE order_id=? AND rider_id=? AND status='OFFERED'",[$mf['order'],$r['id']])->fetch(),'company allocation blocks parallel Maakit offer');
// Opt-in safety is enforced even through the old rider_progress route.
$sf=ready_order($db);$sr=rider($db,$sf,true);$codes=order_safety_codes($db,$sf['a'],['order_id'=>$sf['order']]);Maakit\Api\dispatch_tick($db,$noNetwork);$attempt=Maakit\Api\query($db,"SELECT id FROM mk_dispatch_attempts WHERE order_id=? AND status='OFFERED'",[$sf['order']])->fetchColumn();Maakit\Api\dispatch_accept($db,$sr['auth'],$attempt);rejected(fn()=>Maakit\Api\rider_progress($db,$sr['auth'],['order_id'=>$sf['order'],'operation'=>'pickup']),'INVALID_OTP');Maakit\Api\rider_progress($db,$sr['auth'],['order_id'=>$sf['order'],'operation'=>'pickup','otp'=>$codes['pickup_otp']]);rejected(fn()=>Maakit\Api\rider_progress($db,$sr['auth'],['order_id'=>$sf['order'],'operation'=>'complete','otp'=>$codes['drop_otp']]),'PROOF_REQUIRED');Maakit\Api\rider_progress($db,$sr['auth'],['order_id'=>$sf['order'],'operation'=>'complete','otp'=>$codes['drop_otp'],'proof_base64'=>$image]);check(Maakit\Api\query($db,'SELECT status FROM mk_orders WHERE id=?',[$sf['order']])->fetchColumn()==='DELIVERED','Maakit OTP and proof complete without bypass');
echo "Company isolation, trusted prices, dispatch exclusion, OTP, multi-stop proof and tracking passed.\n";
