<?php
declare(strict_types=1);
namespace Maakit\Api;
use PDO;
use Throwable;
require_once __DIR__.'/sarathi.php';
function company_text($value,int $max=120): string {
    if(!is_string($value)||trim($value)===''||strlen($value)>$max*4||preg_match('/[\x00-\x1F\x7F]/',$value)||preg_match_all('/./us',$value)>$max)throw new ApiError(400,'INVALID_DETAILS','Check names, addresses and reference.');return trim($value);
}
function company_phone($v): string {if(!is_string($v))throw new ApiError(400,'INVALID_DETAILS','Enter an Indian mobile number.');$v=preg_replace('/[ +()-]/','',$v);if(strlen($v)===12&&str_starts_with($v,'91'))$v=substr($v,2);if(!preg_match('/^[6-9][0-9]{9}$/D',$v))throw new ApiError(400,'INVALID_DETAILS','Enter an Indian mobile number.');return '+91'.$v;}
function company_access(PDO $db,array $auth,string $id,bool $active=true,bool $lock=false): array {
    $id=valid_uuid($id);
    if(isset($auth['company_key'])){
        $c=query($db,"SELECT c.* FROM mk_delivery_companies c JOIN mk_company_keys k ON k.company_id=c.id JOIN mk_users u ON u.id=c.owner_id WHERE c.id=? AND k.id=? AND k.revoked_at IS NULL AND k.expires_at>UTC_TIMESTAMP(6) AND u.status='ACTIVE'".($lock?' FOR UPDATE':''),[$id,$auth['company_key']])->fetch();
    }else{$auth=live_identity($db,$auth['claims'],$lock);$c=query($db,'SELECT * FROM mk_delivery_companies WHERE id=? AND owner_id=?'.($lock?' FOR UPDATE':''),[$id,$auth['user_id']])->fetch();}
    if(!$c)throw new ApiError(404,'NOT_FOUND','Company not found.');if($active&&$c['state']!=='ACTIVE')throw new ApiError(403,'COMPANY_NOT_ACTIVE','Your company needs administrator approval.');return $c;
}
function company_admin(array $auth): void {require_roles($auth,['ADMIN']);require_permission($auth,'DISPATCH_WRITE');if(isset($auth['company_key']))throw new ApiError(403,'FORBIDDEN','Company key cannot administer accounts.');}
function company_apply(PDO $db,array $auth,array $body): array {
    require_roles($auth,['CUSTOMER','VENDOR']);$name=company_text($body['name']??null);$phone=company_phone($body['phone']??null);
    $db->beginTransaction();try{$auth=live_identity($db,$auth['claims'],true);$old=query($db,'SELECT id,state FROM mk_delivery_companies WHERE owner_id=? FOR UPDATE',[$auth['user_id']])->fetch();if($old){$db->commit();return $old;}$id=uuid4();query($db,'INSERT INTO mk_delivery_companies(id,owner_id,name,phone) VALUES(?,?,?,?)',[$id,$auth['user_id'],$name,$phone]);$db->commit();return ['id'=>$id,'state'=>'PENDING'];}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function company_list(PDO $db,array $auth): array {
    if(in_array('ADMIN',$auth['roles'],true)){company_admin($auth);return ['companies'=>query($db,'SELECT id,name,phone,state FROM mk_delivery_companies ORDER BY created_at DESC LIMIT 100')->fetchAll(),'stores'=>query($db,'SELECT id,name FROM mk_stores WHERE active=1 ORDER BY name LIMIT 100')->fetchAll(),'riders'=>query($db,"SELECT r.id,u.display_name FROM mk_riders r JOIN mk_users u ON u.id=r.user_id WHERE r.active=1 AND r.kyc_status='VERIFIED' AND u.status='ACTIVE' LIMIT 100")->fetchAll()];}
    if(isset($auth['company_key'])){$c=company_access($db,$auth,$auth['company_id']);$rows=[$c];}else{$rows=query($db,'SELECT id,name,phone,state FROM mk_delivery_companies WHERE owner_id=?',[$auth['user_id']])->fetchAll();}
    foreach($rows as &$c){$c['areas']=query($db,'SELECT a.store_id,s.name,a.base_minor,a.drop_minor,a.radius_m FROM mk_company_areas a JOIN mk_stores s ON s.id=a.store_id WHERE a.company_id=? AND a.active=1 AND s.active=1',[$c['id']])->fetchAll();}unset($c);return ['companies'=>$rows];
}
function company_configure(PDO $db,array $auth,array $b): array {
    company_admin($auth);$id=valid_uuid($b['company_id']??null);$state=$b['state']??null;if(!in_array($state,['ACTIVE','SUSPENDED'],true))throw new ApiError(400,'INVALID_DETAILS','Choose account status.');
    $store=valid_uuid($b['store_id']??null);foreach(['base_minor'=>[0,1000000],'drop_minor'=>[100,1000000],'radius_m'=>[100,50000]] as $k=>$range)if(!is_int($b[$k]??null)||$b[$k]<$range[0]||$b[$k]>$range[1])throw new ApiError(400,'INVALID_DETAILS','Enter valid rates and service radius.');
    $db->beginTransaction();try{$auth=live_identity($db,$auth['claims'],true);company_admin($auth);if(!query($db,'SELECT id FROM mk_delivery_companies WHERE id=? FOR UPDATE',[$id])->fetch())throw new ApiError(404,'NOT_FOUND','Company not found.');
        if(!query($db,"SELECT s.id FROM mk_stores s JOIN mk_vendors v ON v.id=s.vendor_id WHERE s.id=? AND s.active=1 AND v.status='ACTIVE' AND EXISTS(SELECT 1 FROM mk_store_zones z WHERE z.store_id=s.id AND z.fulfillment_type='HYPERLOCAL')",[$store])->fetch())throw new ApiError(409,'AREA_DISABLED','Choose a verified active service shop.');
        query($db,'UPDATE mk_delivery_companies SET state=? WHERE id=?',[$state,$id]);query($db,'INSERT INTO mk_company_areas(company_id,store_id,base_minor,drop_minor,radius_m) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE base_minor=VALUES(base_minor),drop_minor=VALUES(drop_minor),radius_m=VALUES(radius_m),active=1',[$id,$store,$b['base_minor'],$b['drop_minor'],$b['radius_m']]);
        if(isset($b['rider_id'])&&$b['rider_id']!==''){$r=valid_uuid($b['rider_id']);if(!query($db,"SELECT id FROM mk_riders WHERE id=? AND active=1 AND kyc_status='VERIFIED'",[$r])->fetch())throw new ApiError(409,'RIDER_NOT_VERIFIED','Choose an approved delivery partner.');query($db,'INSERT INTO mk_company_riders(company_id,rider_id,active) VALUES(?,?,?) ON DUPLICATE KEY UPDATE active=VALUES(active)',[$id,$r,($b['rider_active']??true)===true?1:0]);}
        row_insert($db,'mk_audit_events',['id'=>uuid4(),'actor_id'=>$auth['user_id'],'action'=>'COMPANY_CONFIGURED','resource_id'=>$id,'details_json'=>json_data(['state'=>$state,'store_id'=>$store,'base_minor'=>$b['base_minor'],'drop_minor'=>$b['drop_minor']])]);$db->commit();return ['saved'=>true];
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function company_key(PDO $db,array $auth,array $b): array {
    if(isset($auth['company_key']))throw new ApiError(403,'FORBIDDEN','Sign in to manage API keys.');$id=valid_uuid($b['company_id']??null);company_access($db,$auth,$id);
    if(isset($b['revoke_id'])){query($db,'UPDATE mk_company_keys SET revoked_at=UTC_TIMESTAMP(6) WHERE id=? AND company_id=?',[valid_uuid($b['revoke_id']),$id]);return ['revoked'=>true];}
    $db->beginTransaction();try{company_access($db,$auth,$id,true,true);query($db,'UPDATE mk_company_keys SET revoked_at=UTC_TIMESTAMP(6) WHERE company_id=? AND revoked_at IS NULL',[$id]);$token='sdc_'.bin2hex(random_bytes(32));$kid=uuid4();query($db,'INSERT INTO mk_company_keys(id,company_id,token_hash,expires_at) VALUES(?,?,?,DATE_ADD(UTC_TIMESTAMP(6),INTERVAL 90 DAY))',[$kid,$id,hash('sha256',$token)]);$db->commit();return ['key_id'=>$kid,'token'=>$token,'expires_in_days'=>90];}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function company_address($b,array $area): array {
    if(!is_array($b))throw new ApiError(400,'INVALID_DETAILS','Enter pickup and drop details.');$result=['name'=>company_text($b['name']??null,80),'phone'=>company_phone($b['phone']??null),'address'=>company_text($b['address']??null,300)];
    foreach(['latitude'=>[-90,90],'longitude'=>[-180,180]] as $k=>$range){$v=$b[$k]??null;if((!is_int($v)&&!is_float($v))||!is_finite((float)$v)||$v<$range[0]||$v>$range[1])throw new ApiError(400,'INVALID_LOCATION','Enter valid map coordinates.');$result[$k]=(float)$v;}
    if(haversine_m((float)$area['latitude'],(float)$area['longitude'],$result['latitude'],$result['longitude'])>(int)$area['radius_m'])throw new ApiError(409,'OUTSIDE_SERVICE_AREA','Pickup and drops must be within your approved service area.');return $result;
}
function company_booking(PDO $db,array $auth,array $b,bool $quoteOnly=false): array {
    $id=valid_uuid($b['company_id']??null);$store=valid_uuid($b['store_id']??null);$fleet=$b['fleet']??'SHARED';if(!in_array($fleet,['SHARED','OWN'],true)||($b['contact_consent']??false)!==true)throw new ApiError(400,'CONSENT_REQUIRED','Confirm you may share the recipient details.');
    $db->beginTransaction();try{company_access($db,$auth,$id,true,true);$area=query($db,"SELECT a.*,s.latitude,s.longitude FROM mk_company_areas a JOIN mk_stores s ON s.id=a.store_id JOIN mk_vendors v ON v.id=s.vendor_id WHERE a.company_id=? AND a.store_id=? AND a.active=1 AND s.active=1 AND v.status='ACTIVE' FOR UPDATE",[$id,$store])->fetch();if(!$area)throw new ApiError(409,'AREA_DISABLED','Ask the administrator to enable a service area.');
        $pickup=company_address($b['pickup']??null,$area);$raw=$b['stops']??null;if(!is_array($raw)||!array_is_list($raw)||count($raw)<1||count($raw)>10)throw new ApiError(400,'INVALID_STOPS','Enter one to ten delivery stops.');$stops=array_map(fn($s)=>company_address($s,$area),$raw);
        $emergency=[];$contacts=$b['emergency_contacts']??[];if(!is_array($contacts)||!array_is_list($contacts)||count($contacts)>3)throw new ApiError(400,'INVALID_DETAILS','Enter up to three authorised emergency contacts.');foreach($contacts as $c){if(!is_array($c))throw new ApiError(400,'INVALID_DETAILS','Check contacts.');$emergency[]=['name'=>company_text($c['name']??null,80),'phone'=>company_phone($c['phone']??null)];}
        $fee=(int)$area['base_minor']+count($stops)*(int)$area['drop_minor'];if($quoteOnly){$db->commit();return ['fee_minor'=>$fee,'currency'=>'INR','goods_collection'=>false,'pricing'=>'APPROVED_AREA_FLAT_RATE'];}
        $reference=company_text($b['reference']??null,80);$fp=hash('sha256',json_data([$store,$fleet,$pickup,$stops,$emergency]));$old=query($db,'SELECT id,state,fee_minor,fingerprint FROM mk_company_deliveries WHERE company_id=? AND reference=? FOR UPDATE',[$id,$reference])->fetch();if($old){if(!hash_equals($old['fingerprint'],$fp))throw new ApiError(409,'IDEMPOTENCY_CONFLICT','Use a new reference for a different delivery.');unset($old['fingerprint']);$db->commit();return $old+['replayed'=>true];}
        $bid=uuid4();$track=bin2hex(random_bytes(32));$pickupCode=(string)random_int(100000,999999);$codes=[];
        query($db,'INSERT INTO mk_company_deliveries(id,company_id,store_id,reference,fingerprint,fleet,pickup_json,emergency_json,pickup_hash,otp_expires_at,fee_minor,tracking_hash,tracking_expires_at) VALUES(?,?,?,?,?,?,?,?,?,DATE_ADD(UTC_TIMESTAMP(6),INTERVAL 24 HOUR),?,?,DATE_ADD(UTC_TIMESTAMP(6),INTERVAL 48 HOUR))',[$bid,$id,$store,$reference,$fp,$fleet,json_data($pickup),json_data($emergency),password_hash($pickupCode,PASSWORD_DEFAULT),$fee,hash('sha256',$track)]);
        foreach($stops as $i=>$stop){$code=(string)random_int(100000,999999);$codes[]=['stop'=>$i+1,'otp'=>$code];query($db,'INSERT INTO mk_company_stops(delivery_id,sequence_no,address_json,otp_hash) VALUES(?,?,?,?)',[$bid,$i+1,json_data($stop),password_hash($code,PASSWORD_DEFAULT)]);}
        $db->commit();return ['id'=>$bid,'state'=>'REQUESTED','fee_minor'=>$fee,'pickup_otp'=>$pickupCode,'drop_otps'=>$codes,'tracking_url'=>settings()['site_url'].'/public/company-track.php#'.$track,'replayed'=>false];
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function company_orders(PDO $db,array $auth,string $cid): array {company_access($db,$auth,$cid,false);$rows=query($db,'SELECT b.id,b.reference,b.state,b.fleet,b.fee_minor,b.next_stop,b.created_at,b.delivered_at,(SELECT COUNT(*) FROM mk_company_stops s WHERE s.delivery_id=b.id AND s.delivered_at IS NOT NULL) AS completed_stops FROM mk_company_deliveries b WHERE company_id=? ORDER BY created_at DESC LIMIT 100',[$cid])->fetchAll();$summary=query($db,"SELECT COUNT(*) AS delivered,COALESCE(SUM(fee_minor),0) AS delivered_fee_minor FROM mk_company_deliveries WHERE company_id=? AND state='DELIVERED'",[$cid])->fetch();return ['deliveries'=>$rows,'summary'=>$summary];}
function company_cancel(PDO $db,array $auth,array $b): array {$id=valid_uuid($b['delivery_id']??null);$cid=valid_uuid($b['company_id']??null);$db->beginTransaction();try{company_access($db,$auth,$cid,true,true);$row=query($db,'SELECT * FROM mk_company_deliveries WHERE id=? AND company_id=? FOR UPDATE',[$id,$cid])->fetch();if(!$row)throw new ApiError(404,'NOT_FOUND','Delivery not found.');if(!in_array($row['state'],['REQUESTED','OFFERED','CANCELLED'],true))throw new ApiError(409,'ALREADY_ASSIGNED','Ask support to review an accepted delivery.');if($row['offered_rider_id'])query($db,'SELECT id FROM mk_riders WHERE id=? FOR UPDATE',[$row['offered_rider_id']]);query($db,"UPDATE mk_company_deliveries SET state='CANCELLED',offered_rider_id=NULL,offer_expires_at=NULL WHERE id=?",[$id]);$db->commit();return ['state'=>'CANCELLED'];}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
function company_busy(PDO $db,string $rider): bool {return (bool)query($db,"SELECT id FROM mk_company_deliveries WHERE rider_id=? AND state IN ('ASSIGNED','PICKED_UP') OR offered_rider_id=? AND state='OFFERED' AND offer_expires_at>UTC_TIMESTAMP(6) LIMIT 1 FOR UPDATE",[$rider,$rider])->fetch();}
function company_tick(PDO $db): int {
    $ids=query($db,"SELECT id FROM mk_company_deliveries WHERE state='REQUESTED' OR state='OFFERED' AND offer_expires_at<=UTC_TIMESTAMP(6) ORDER BY created_at LIMIT 20")->fetchAll(PDO::FETCH_COLUMN);$count=0;
    foreach($ids as $id){$db->beginTransaction();try{$b=query($db,'SELECT * FROM mk_company_deliveries WHERE id=? FOR UPDATE',[$id])->fetch();if(!$b||!in_array($b['state'],['REQUESTED','OFFERED'],true)){$db->commit();continue;}
        if($b['state']==='OFFERED'){if(strtotime($b['offer_expires_at'].' UTC')>time()){$db->commit();continue;}query($db,'SELECT id FROM mk_riders WHERE id=? FOR UPDATE',[$b['offered_rider_id']]);query($db,"UPDATE mk_company_deliveries SET state='REQUESTED',last_rider_id=offered_rider_id,offered_rider_id=NULL,offer_expires_at=NULL WHERE id=?",[$id]);$b['last_rider_id']=$b['offered_rider_id'];}
        if(!query($db,"SELECT c.id FROM mk_delivery_companies c JOIN mk_company_areas a ON a.company_id=c.id JOIN mk_stores s ON s.id=a.store_id JOIN mk_vendors v ON v.id=s.vendor_id WHERE c.id=? AND c.state='ACTIVE' AND a.store_id=? AND a.active=1 AND s.active=1 AND v.status='ACTIVE'",[$b['company_id'],$b['store_id']])->fetch()){$db->commit();continue;}
        $fleet=$b['fleet']==='OWN'?"EXISTS(SELECT 1 FROM mk_company_riders cr WHERE cr.company_id=? AND cr.rider_id=r.id AND cr.active=1)":"r.vendor_id IS NULL AND NOT EXISTS(SELECT 1 FROM mk_company_riders cr WHERE cr.rider_id=r.id AND cr.active=1)";
        $params=[$b['store_id']];if($b['fleet']==='OWN')$params[]=$b['company_id'];
        $riders=query($db,"SELECT r.id FROM mk_riders r JOIN mk_rider_duty d ON d.rider_id=r.id JOIN mk_users u ON u.id=r.user_id JOIN mk_rider_zones z ON z.rider_id=r.id JOIN mk_stores area ON area.id=z.store_id LEFT JOIN mk_partner_locations gps ON gps.rider_id=r.id WHERE z.store_id=? AND z.fulfillment_type='HYPERLOCAL' AND z.active=1 AND r.active=1 AND r.kyc_status='VERIFIED' AND u.status='ACTIVE' AND d.available_until>UTC_TIMESTAMP(6) AND $fleet ORDER BY CASE WHEN gps.updated_at>DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 60 SECOND) THEN 0 ELSE 1 END,CASE WHEN gps.updated_at>DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 60 SECOND) THEN POW(gps.latitude-area.latitude,2)+POW((gps.longitude-area.longitude)*COS(RADIANS(area.latitude)),2) ELSE 999999 END,r.id LIMIT 100",$params)->fetchAll(PDO::FETCH_COLUMN);
        // All allocations lock the same rider row before checking either work queue.
        foreach($riders as $rid){if($rid===$b['last_rider_id']&&count($riders)>1)continue;query($db,'SELECT id FROM mk_riders WHERE id=? FOR UPDATE',[$rid]);if(company_busy($db,$rid)||query($db,'SELECT id FROM mk_rider_slots WHERE rider_id=? FOR UPDATE',[$rid])->fetch())continue;
            query($db,"UPDATE mk_company_deliveries SET state='OFFERED',offered_rider_id=?,offer_expires_at=DATE_ADD(UTC_TIMESTAMP(6),INTERVAL 60 SECOND) WHERE id=?",[$rid,$id]);$count++;break;}
        $db->commit();
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log('Company dispatch deferred class='.get_class($e));}}
    return $count;
}
function company_partner(PDO $db,array $auth): array {$r=sarathi_rider($db,$auth);$rows=query($db,"SELECT b.id AS delivery_id,b.state,b.reference,b.fee_minor,b.next_stop,b.offer_expires_at,c.name AS company_name FROM mk_company_deliveries b JOIN mk_delivery_companies c ON c.id=b.company_id WHERE ((c.state='ACTIVE' AND b.offered_rider_id=? AND b.state='OFFERED' AND b.offer_expires_at>UTC_TIMESTAMP(6)) OR (b.rider_id=? AND b.state IN ('ASSIGNED','PICKED_UP'))) LIMIT 20",[$r['id'],$r['id']])->fetchAll();
    foreach($rows as &$b){if($b['state']!=='OFFERED'){$full=query($db,'SELECT pickup_json,emergency_json FROM mk_company_deliveries WHERE id=?',[$b['delivery_id']])->fetch();$b['pickup']=json_decode($full['pickup_json'],true);$b['emergency_contacts']=json_decode($full['emergency_json'],true);$b['stops']=query($db,'SELECT sequence_no,address_json,delivered_at FROM mk_company_stops WHERE delivery_id=? ORDER BY sequence_no',[$b['delivery_id']])->fetchAll();foreach($b['stops'] as &$s){$s['address']=json_decode($s['address_json'],true);unset($s['address_json']);}unset($s);}}unset($b);return $rows;
}
function company_accept(PDO $db,array $auth,array $b): array {$id=valid_uuid($b['delivery_id']??null);$db->beginTransaction();try{$auth=live_identity($db,$auth['claims'],true);$r=sarathi_rider($db,$auth);$row=query($db,'SELECT *,offer_expires_at>UTC_TIMESTAMP(6) AS fresh FROM mk_company_deliveries WHERE id=? FOR UPDATE',[$id])->fetch();query($db,'SELECT id FROM mk_riders WHERE id=? FOR UPDATE',[$r['id']]);if(!$row)throw new ApiError(404,'NOT_FOUND','Offer not found.');if($row['rider_id']===$r['id']&&in_array($row['state'],['ASSIGNED','PICKED_UP','DELIVERED'],true)){$db->commit();return ['accepted'=>true,'replayed'=>true];}
        if($row['offered_rider_id']!==$r['id'])throw new ApiError(404,'NOT_FOUND','Offer not found.');if($row['state']!=='OFFERED'||!$row['fresh']||query($db,'SELECT id FROM mk_rider_slots WHERE rider_id=? FOR UPDATE',[$r['id']])->fetch()||!query($db,"SELECT id FROM mk_rider_duty WHERE rider_id=? AND available_until>UTC_TIMESTAMP(6)",[$r['id']])->fetch()||!query($db,"SELECT c.id FROM mk_delivery_companies c JOIN mk_company_areas a ON a.company_id=c.id WHERE c.id=? AND c.state='ACTIVE' AND a.store_id=? AND a.active=1",[$row['company_id'],$row['store_id']])->fetch())throw new ApiError(409,'OFFER_EXPIRED','Refresh your offers.');
        if(!query($db,"SELECT id FROM mk_rider_zones WHERE rider_id=? AND store_id=? AND active=1 AND fulfillment_type='HYPERLOCAL'",[$r['id'],$row['store_id']])->fetch())throw new ApiError(409,'OFFER_EXPIRED','Service area changed.');
        if(query($db,"SELECT id FROM mk_company_deliveries WHERE id<>? AND (rider_id=? AND state IN ('ASSIGNED','PICKED_UP') OR offered_rider_id=? AND state='OFFERED' AND offer_expires_at>UTC_TIMESTAMP(6)) LIMIT 1 FOR UPDATE",[$id,$r['id'],$r['id']])->fetch())throw new ApiError(409,'ASSIGNMENT_CHANGED','Finish your current delivery first.');
        if($row['fleet']==='SHARED'&&query($db,'SELECT vendor_id FROM mk_riders WHERE id=?',[$r['id']])->fetchColumn()!==null)throw new ApiError(409,'OFFER_EXPIRED','Fleet changed.');
        if($row['fleet']==='SHARED'&&query($db,'SELECT rider_id FROM mk_company_riders WHERE rider_id=? AND active=1',[$r['id']])->fetch())throw new ApiError(409,'OFFER_EXPIRED','Fleet changed.');
        if($row['fleet']==='OWN'&&!query($db,'SELECT rider_id FROM mk_company_riders WHERE company_id=? AND rider_id=? AND active=1',[$row['company_id'],$r['id']])->fetch())throw new ApiError(409,'OFFER_EXPIRED','Company fleet changed.');
        query($db,"UPDATE mk_company_deliveries SET state='ASSIGNED',rider_id=?,offered_rider_id=NULL,offer_expires_at=NULL WHERE id=?",[$r['id'],$id]);$db->commit();return ['accepted'=>true,'replayed'=>false];
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
function company_proof($value): array {
    if(!is_string($value)||strlen($value)>700000)throw new ApiError(400,'PROOF_REQUIRED','Attach a JPEG or PNG proof under 500 KB.');$raw=base64_decode($value,true);if($raw===false||strlen($raw)>512000||strlen($raw)<20)throw new ApiError(400,'PROOF_REQUIRED','Attach a JPEG or PNG proof under 500 KB.');$info=@getimagesizefromstring($raw);if(!$info||!in_array($info['mime'],['image/jpeg','image/png'],true)||$info[0]>8000||$info[1]>8000)throw new ApiError(400,'INVALID_PROOF','Choose a valid JPEG or PNG photo.');return [$raw,$info['mime'],hash('sha256',$raw)];
}
function company_progress(PDO $db,array $auth,array $b): array {
    $id=valid_uuid($b['delivery_id']??null);$op=$b['operation']??null;if(!in_array($op,['pickup','drop'],true))throw new ApiError(400,'INVALID_DECISION','Choose pickup or drop.');
    $db->beginTransaction();try{$auth=live_identity($db,$auth['claims'],true);$r=sarathi_rider($db,$auth);$row=query($db,'SELECT *,otp_expires_at>UTC_TIMESTAMP(6) AS otp_fresh FROM mk_company_deliveries WHERE id=? AND rider_id=? FOR UPDATE',[$id,$r['id']])->fetch();if(!$row)throw new ApiError(404,'NOT_FOUND','Assigned delivery not found.');
        $seq=$b['stop']??null;if($op==='pickup'&&in_array($row['state'],['PICKED_UP','DELIVERED'],true)){$db->commit();return ['state'=>$row['state'],'replayed'=>true];}
        if($op==='drop'&&is_int($seq)){$done=query($db,'SELECT delivered_at FROM mk_company_stops WHERE delivery_id=? AND sequence_no=?',[$id,$seq])->fetch();if($done&&$done['delivered_at']){$db->commit();return ['state'=>$row['state'],'replayed'=>true];}}
        if(($op==='pickup'&&$row['state']!=='ASSIGNED')||($op==='drop'&&($row['state']!=='PICKED_UP'||!is_int($seq)||$seq!==(int)$row['next_stop'])))throw new ApiError(409,'INVALID_TRANSITION','Confirm pickup and follow the drop order.');
        if(!$row['otp_fresh'])throw new ApiError(409,'OTP_EXPIRED','Ask the company to contact support.');$target=$op==='pickup'?$row:query($db,'SELECT * FROM mk_company_stops WHERE delivery_id=? AND sequence_no=? FOR UPDATE',[$id,$seq])->fetch();$attempts=$op==='pickup'?(int)$target['pickup_attempts']:(int)$target['otp_attempts'];if($attempts>=5)throw new ApiError(429,'OTP_LOCKED','Too many attempts. Contact support.');
        $code=$b['otp']??null;$hash=$op==='pickup'?$target['pickup_hash']:$target['otp_hash'];if(!is_string($code)||!preg_match('/^[0-9]{6}$/D',$code)||!password_verify($code,$hash)){
            if($op==='pickup')query($db,'UPDATE mk_company_deliveries SET pickup_attempts=pickup_attempts+1 WHERE id=?',[$id]);else query($db,'UPDATE mk_company_stops SET otp_attempts=otp_attempts+1 WHERE delivery_id=? AND sequence_no=?',[$id,$seq]);$db->commit();throw new ApiError(400,'INVALID_OTP','Check the six-digit code with the recipient.');}
        if($op==='pickup'){query($db,"UPDATE mk_company_deliveries SET state='PICKED_UP' WHERE id=?",[$id]);$state='PICKED_UP';}else{[$proof,$mime,$sha]=company_proof($b['proof_base64']??null);query($db,'UPDATE mk_company_stops SET delivered_at=UTC_TIMESTAMP(6),proof_blob=?,proof_mime=?,proof_sha=? WHERE delivery_id=? AND sequence_no=?',[$proof,$mime,$sha,$id,$seq]);$left=query($db,'SELECT sequence_no FROM mk_company_stops WHERE delivery_id=? AND delivered_at IS NULL ORDER BY sequence_no LIMIT 1',[$id])->fetchColumn();$state=$left===false?'DELIVERED':'PICKED_UP';if($state==='DELIVERED'){query($db,'SELECT id FROM mk_riders WHERE id=? FOR UPDATE',[$r['id']]);query($db,"UPDATE mk_company_deliveries SET state='DELIVERED',delivered_at=UTC_TIMESTAMP(6) WHERE id=?",[$id]);}else query($db,'UPDATE mk_company_deliveries SET next_stop=? WHERE id=?',[$left,$id]);}
        $db->commit();return ['state'=>$state,'replayed'=>false];
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function company_tracking(PDO $db,string $token): array {
    if(!preg_match('/^[a-f0-9]{64}$/D',$token))throw new ApiError(404,'NOT_FOUND','Tracking link unavailable.');$b=query($db,'SELECT id,state,rider_id,next_stop FROM mk_company_deliveries WHERE tracking_hash=? AND tracking_expires_at>UTC_TIMESTAMP(6)',[hash('sha256',$token)])->fetch();if(!$b)throw new ApiError(404,'NOT_FOUND','Tracking link expired.');$location=null;if(in_array($b['state'],['ASSIGNED','PICKED_UP'],true))$location=query($db,"SELECT latitude,longitude,accuracy_m,updated_at FROM mk_partner_locations WHERE rider_id=? AND updated_at>DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 60 SECOND)",[$b['rider_id']])->fetch()?:null;return ['state'=>$b['state'],'next_stop'=>(int)$b['next_stop'],'location'=>$location];
}
function company_codes(PDO $db,array $auth,array $b): array {
    $cid=valid_uuid($b['company_id']??null);$id=valid_uuid($b['delivery_id']??null);$db->beginTransaction();try{company_access($db,$auth,$cid,true,true);$row=query($db,'SELECT * FROM mk_company_deliveries WHERE id=? AND company_id=? FOR UPDATE',[$id,$cid])->fetch();if(!$row)throw new ApiError(404,'NOT_FOUND','Delivery not found.');if(!in_array($row['state'],['REQUESTED','OFFERED','ASSIGNED','PICKED_UP'],true))throw new ApiError(409,'INVALID_TRANSITION','Codes cannot be changed after completion.');$code=(string)random_int(100000,999999);$track=bin2hex(random_bytes(32));query($db,'UPDATE mk_company_deliveries SET pickup_hash=?,pickup_attempts=0,otp_expires_at=DATE_ADD(UTC_TIMESTAMP(6),INTERVAL 24 HOUR),tracking_hash=?,tracking_expires_at=DATE_ADD(UTC_TIMESTAMP(6),INTERVAL 48 HOUR) WHERE id=?',[password_hash($code,PASSWORD_DEFAULT),hash('sha256',$track),$id]);$stops=query($db,'SELECT sequence_no FROM mk_company_stops WHERE delivery_id=? AND delivered_at IS NULL ORDER BY sequence_no',[$id])->fetchAll(PDO::FETCH_COLUMN);$codes=[];foreach($stops as $seq){$otp=(string)random_int(100000,999999);query($db,'UPDATE mk_company_stops SET otp_hash=?,otp_attempts=0 WHERE delivery_id=? AND sequence_no=?',[password_hash($otp,PASSWORD_DEFAULT),$id,$seq]);$codes[]=['stop'=>(int)$seq,'otp'=>$otp];}$db->commit();return ['id'=>$id,'pickup_otp'=>$code,'drop_otps'=>$codes,'tracking_url'=>settings()['site_url'].'/public/company-track.php#'.$track];}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function company_view_proof(PDO $db,array $auth,string $cid,string $id,int $stop): array {company_access($db,$auth,$cid,false);$r=query($db,'SELECT s.proof_blob,s.proof_mime,s.proof_sha,s.delivered_at FROM mk_company_stops s JOIN mk_company_deliveries b ON b.id=s.delivery_id WHERE b.id=? AND b.company_id=? AND s.sequence_no=? AND s.delivered_at IS NOT NULL',[valid_uuid($id),$cid,$stop])->fetch();if(!$r)throw new ApiError(404,'NOT_FOUND','Proof not found.');return ['base64'=>base64_encode($r['proof_blob']),'mime'=>$r['proof_mime'],'sha256'=>$r['proof_sha'],'delivered_at'=>$r['delivered_at']];}
