<?php
require_once __DIR__.'/../inc/fn.php';
$company_admin_page=isset($company_admin_page)&&$company_admin_page===true;
if($company_admin_page)need_role('admin');elseif(!cust())redirect('/account.php');
$page_title=t('Sarathi Business Delivery','सारथी Business Delivery');
include __DIR__.'/../inc/head.php';
$labels=['fleetactive'=>t('Company fleet access','कंपनी fleet access'),'approve'=>t('Save approval / service area','Approval / service area सेव करें'),'company'=>t('Company','कंपनी'),'area'=>t('Service area','Service area'),'base'=>t('Base fee (paise)','Base शुल्क (पैसे)'),'perdrop'=>t('Per drop fee (paise)','हर drop शुल्क (पैसे)'),'radius'=>t('Service radius (metres)','Service radius (मीटर)'),'rider'=>t('Own fleet partner (optional)','अपना fleet partner (वैकल्पिक)'),'loading'=>t('Loading…','लोड हो रहा है…'),'saved'=>t('Saved','सेव हो गया'),'error'=>t('Please check the details or account approval and try again.','जानकारी और account approval जाँचकर फिर प्रयास करें।'),'pending'=>t('Administrator approval is pending.','Admin approval बाकी है।'),'book'=>t('Book delivery','डिलीवरी बुक करें'),'quote'=>t('Check delivery fee','डिलीवरी शुल्क देखें'),'name'=>t('Name','नाम'),'phone'=>t('Mobile','मोबाइल'),'address'=>t('Address','पता'),'lat'=>t('Latitude','Latitude'),'lon'=>t('Longitude','Longitude'),'cancel'=>t('Cancel','रद्द करें'),'codes'=>t('Send pickup code to sender and each drop code only to that recipient. Codes expire after 24 hours.','Pickup code भेजने वाले को और हर drop code केवल उसके recipient को दें। Code 24 घंटे तक मान्य है।'),'proof'=>t('View delivery proof','Delivery proof देखें'),'key'=>t('Copy this secret now; it will not be shown again. Keep it on your server, never in browser code. Generating a key revokes older keys.','यह secret अभी सुरक्षित रख लें; दोबारा नहीं दिखेगा। इसे server पर रखें, browser code में नहीं। नया key पुराने keys बंद कर देगा।'),'reference'=>t('Unique order reference','अलग order reference'),'state'=>t('Status','स्थिति'),'fee'=>t('Delivery fee','डिलीवरी शुल्क'),'delivered'=>t('Completed deliveries / fees recorded, not payment settlement','पूरी deliveries / दर्ज शुल्क; यह भुगतान मिलने की पुष्टि नहीं है'),'consent'=>t('I am authorised to share these recipient and emergency contact details.','मैं recipient और emergency contact की जानकारी साझा करने के लिए अधिकृत हूँ।'),'add'=>t('Add drop','Drop जोड़ें'),'new'=>t('New booking','नई booking'),'pickup'=>t('Pickup details','Pickup जानकारी'),'drop'=>t('Drop','Drop'),'contact'=>t('Customer family contact (optional)','Customer का family contact (वैकल्पिक)'),'recover'=>t('Refresh codes / tracking link before pickup','Pickup से पहले codes / tracking link फिर बनाएं')];
?>
<main class="wrap" style="max-width:1000px" data-csrf="<?= h(csrf()) ?>" data-company-context="<?= $company_admin_page?'staff':'customer' ?>">
<h1><?= h($page_title) ?></h1><p><?= t('Company parcels use a separate booking flow. Goods payment stays directly with the company; Sarathi records only delivery charges.','कंपनी के parcels की अलग booking होगी। सामान का पैसा सीधे कंपनी को मिलेगा; सारथी केवल delivery शुल्क दर्ज करेगा।') ?></p>
<p id="company-status" role="status" aria-live="polite"></p><div id="company-list"></div>
<?php if(!$company_admin_page): ?>
<form id="company-apply" class="box" hidden><h2><?= t('Register your company','अपनी कंपनी जोड़ें') ?></h2><label><?= t('Company name','कंपनी का नाम') ?><input name="name" maxlength="120" required></label><label><?= t('Contact mobile','संपर्क मोबाइल') ?><input name="phone" type="tel" required></label><button class="btn btn-brand"><?= t('Request approval','Approval माँगें') ?></button></form>
<section id="company-work" hidden><div class="box"><h2><?= t('New parcel delivery','नई parcel delivery') ?></h2><form id="company-book">
<label><?= t('Approved service area','मंजूर service area') ?><select name="store_id" required></select></label>
<label><?= t('Delivery partners','Delivery partners') ?><select name="fleet"><option value="SHARED"><?= t('Sarathi partner pool','सारथी partner pool') ?></option><option value="OWN"><?= t('Approved company staff','मंजूर कंपनी staff') ?></option></select></label>
<label><?= t('Order reference','Order reference') ?><input name="reference" maxlength="80" required></label><div id="company-pickup"></div><div id="company-stops"></div>
<button id="company-add-stop" type="button" class="btn btn-line"><?= t('Add another drop (maximum 10)','एक और drop जोड़ें (अधिकतम 10)') ?></button>
<label><?= t('Customer family contact name (optional)','Customer family contact का नाम (वैकल्पिक)') ?><input name="emergency_name" maxlength="80"></label><label><?= t('Family mobile','Family मोबाइल') ?><input name="emergency_phone" type="tel"></label>
<label><input name="consent" type="checkbox" required> <?= h($labels['consent']) ?></label>
<p><?= t('JPEG / PNG proof and recipient OTP are required at every drop. Delivery fee follows the approved area rate; it is not a road-distance quote.','हर drop पर recipient OTP और JPEG / PNG proof जरूरी है। Delivery शुल्क मंजूर area rate से तय होगा; यह सड़क की दूरी का किराया नहीं है।') ?></p>
<button id="company-quote" type="button" class="btn btn-line"><?= h($labels['quote']) ?></button><button class="btn btn-brand"><?= h($labels['book']) ?></button></form><div id="company-receipt"></div></div>
<div class="box"><h2><?= t('Company orders and account','कंपनी orders और हिसाब') ?></h2><div id="company-orders"></div><button id="company-refresh" class="btn btn-line"><?= t('Refresh orders','Orders फिर देखें') ?></button></div>
<div class="box"><h2><?= t('Connect your software','अपना software जोड़ें') ?></h2><p><?= t('A key can create, quote, list and cancel your company deliveries only. It cannot administer accounts or control a rider.','Key केवल आपकी कंपनी की delivery बनाना, शुल्क देखना, सूची और cancellation कर सकता है। इससे admin या rider का काम नहीं किया जा सकता।') ?></p><button id="company-key" class="btn btn-line"><?= t('Generate / replace API key','API key बनाएं / बदलें') ?></button><div id="company-key-result"></div></div></section>
<?php endif; ?>
<p><a href="<?= $company_admin_page?'/admin/index.php':'/account.php' ?>"><?= t('Back to account','खाते पर वापस जाएं') ?></a></p>
</main><script type="application/json" id="company-labels"><?= json_encode($labels,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE) ?></script>
<script src="/assets/maakit-api.js" defer></script><script src="/assets/company-delivery.js" defer></script>
<?php include __DIR__.'/../inc/foot.php'; ?>
