SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS courier_tracking (
 order_id INT PRIMARY KEY,
 carrier VARCHAR(80) NOT NULL,
 tracking_no VARCHAR(100) NOT NULL,
 updated_by INT NOT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
