-- 021: Branded and additional everyday discovery templates in existing shop types.
-- No shop availability, prices, offers or photographs are inserted.
-- Pack/variant choice and price remain the shopkeeper's confirmation.
-- Brand-family references checked 2026-10-08 (names only, no copied media):
-- https://itcportal.com/itc-businesses/fmcg.html
-- https://itcportal.com/itc-businesses/fmcg/food.html
-- https://www.hul.co.in/brands/
-- https://www.hul.co.in/brands/2/
-- https://www.dove-india.com/collections/hair-care
-- https://amul.com/  / https://shop.amul.com/
-- https://www.boat-lifestyle.com/
-- https://www.kokuyocamlin.com/camel/paints/artist-water-colours
-- https://www.kokuyocamlin.com/camel/drawing-materials
-- https://shop.ttkprestige.com/cookware.html
-- https://www.pidilite.com/consumer-brands/fevikwik
-- https://www.pidilite.com/about
-- https://www.pedigree.in/dog-products/all
-- https://onlineportal.havells.com/custHavellsLogonPage/customerLogonPage_BKP_Original.html
SET NAMES utf8mb4;
INSERT IGNORE INTO catalog_items
(id,shop_type,sub_cat,name_en,name_hi,unit_hint,is_sewa,sort_no) VALUES
(1517,'Grocery / Kirana Store','Atta & Flour','Aashirvaad Wheat Atta','आशीर्वाद गेहूँ आटा','पैक',0,1517),
(1518,'Grocery / Kirana Store','Atta & Flour','Aashirvaad Multigrain Atta','आशीर्वाद मल्टीग्रेन आटा','पैक',0,1518),
(1519,'Grocery / Kirana Store','Atta & Flour','Aashirvaad Besan','आशीर्वाद बेसन','पैक',0,1519),
(1520,'Grocery / Kirana Store','Atta & Flour','Aashirvaad Suji Rava','आशीर्वाद सूजी रवा','पैक',0,1520),
(1521,'Grocery / Kirana Store','Atta & Flour','Aashirvaad Ragi Flour','आशीर्वाद रागी आटा','पैक',0,1521),
(1522,'Grocery / Kirana Store','Snacks & Packaged Food','Sunfeast Biscuits','सनफीस्ट बिस्कुट','पैक',0,1522),
(1523,'Grocery / Kirana Store','Snacks & Packaged Food','Bingo Potato Chips','बिंगो आलू चिप्स','पैक',0,1523),
(1524,'Grocery / Kirana Store','Snacks & Packaged Food','YiPPee Noodles','यिप्पी नूडल्स','पैक',0,1524),
(1525,'Grocery / Kirana Store','Snacks & Packaged Food','Aashirvaad Vermicelli','आशीर्वाद सेवई','पैक',0,1525),
(1526,'Grocery / Kirana Store','Beverages','Brooke Bond Red Label Tea','ब्रुक बॉन्ड रेड लेबल चाय','पैक',0,1526),
(1527,'Grocery / Kirana Store','Beverages','Brooke Bond Taaza Tea','ब्रुक बॉन्ड ताज़ा चाय','पैक',0,1527),
(1528,'Grocery / Kirana Store','Beverages','Bru Instant Coffee','ब्रू इंस्टेंट कॉफी','पैक',0,1528),
(1529,'Dairy Shop','Milk & Milk Products','Amul Milk','अमूल दूध','पैक',0,1529),
(1530,'Dairy Shop','Milk & Milk Products','Amul Butter','अमूल मक्खन','पैक',0,1530),
(1531,'Dairy Shop','Milk & Milk Products','Amul Cheese','अमूल चीज़','पैक',0,1531),
(1532,'Dairy Shop','Milk & Milk Products','Amul Paneer','अमूल पनीर','पैक',0,1532),
(1533,'Dairy Shop','Milk & Milk Products','Amul Curd','अमूल दही','पैक',0,1533),
(1534,'Dairy Shop','Milk & Milk Products','Amul Ghee','अमूल घी','पैक',0,1534),
(1535,'Dairy Shop','Milk & Milk Products','Amul Fresh Cream','अमूल फ्रेश क्रीम','पैक',0,1535),
(1536,'Cleaning Products Store','Cleaning Supplies','Surf Excel Detergent Powder','सर्फ एक्सेल डिटर्जेंट पाउडर','पैक',0,1536),
(1537,'Cleaning Products Store','Cleaning Supplies','Surf Excel Matic Liquid','सर्फ एक्सेल मैटिक लिक्विड','पैक',0,1537),
(1538,'Cleaning Products Store','Cleaning Supplies','Rin Detergent','रिन डिटर्जेंट','पैक',0,1538),
(1539,'Cleaning Products Store','Cleaning Supplies','Wheel Detergent Powder','व्हील डिटर्जेंट पाउडर','पैक',0,1539),
(1540,'Cleaning Products Store','Cleaning Supplies','Vim Dishwash Bar','विम बर्तन धोने की टिकिया','पैक',0,1540),
(1541,'Cleaning Products Store','Cleaning Supplies','Vim Dishwash Liquid','विम बर्तन धोने का लिक्विड','पैक',0,1541),
(1542,'Cleaning Products Store','Cleaning Supplies','Comfort Fabric Conditioner','कम्फर्ट फैब्रिक कंडीशनर','पैक',0,1542),
(1543,'Cleaning Products Store','Cleaning Supplies','Domex Toilet Cleaner','डोमेक्स टॉयलेट क्लीनर','पैक',0,1543),
(1544,'Cosmetics & Beauty Store','Hair Care','Dove Shampoo','डव शैम्पू','पैक',0,1544),
(1545,'Cosmetics & Beauty Store','Hair Care','Dove Conditioner','डव कंडीशनर','पैक',0,1545),
(1546,'Cosmetics & Beauty Store','Hair Care','Clinic Plus Shampoo','क्लिनिक प्लस शैम्पू','पैक',0,1546),
(1547,'Cosmetics & Beauty Store','Hair Care','Sunsilk Shampoo','सनसिल्क शैम्पू','पैक',0,1547),
(1548,'Cosmetics & Beauty Store','Hair Care','Tresemme Shampoo','ट्रेसमे शैम्पू','पैक',0,1548),
(1549,'Cosmetics & Beauty Store','Skin Care','Dove Beauty Bar','डव ब्यूटी बार साबुन','पैक',0,1549),
(1550,'Cosmetics & Beauty Store','Skin Care','Lux Soap','लक्स साबुन','पैक',0,1550),
(1551,'Cosmetics & Beauty Store','Skin Care','Lifebuoy Soap','लाइफबॉय साबुन','पैक',0,1551),
(1552,'Cosmetics & Beauty Store','Skin Care','Vaseline Body Lotion','वैसलीन बॉडी लोशन','पैक',0,1552),
(1553,'Cosmetics & Beauty Store','Skin Care','Ponds Cold Cream','पॉन्ड्स कोल्ड क्रीम','पैक',0,1553),
(1554,'Book & Stationery Shop','Stationery','Classmate Notebook','क्लासमेट कॉपी','पैक',0,1554),
(1555,'Book & Stationery Shop','Stationery','Paperkraft Notebook','पेपरक्राफ्ट कॉपी','पैक',0,1555),
(1556,'Book & Stationery Shop','Stationery','Camel Artist Water Colours','कैमल आर्टिस्ट वाटर कलर','पैक',0,1556),
(1557,'Book & Stationery Shop','Stationery','Camel Colour Pencils','कैमल रंगीन पेंसिल','पैक',0,1557),
(1558,'Book & Stationery Shop','Stationery','Fevikwik Instant Adhesive','फेवीक्विक इंस्टेंट गोंद','पैक',0,1558),
(1559,'Book & Stationery Shop','Stationery','Whiteboard Marker','व्हाइटबोर्ड मार्कर','पैक',0,1559),
(1560,'Book & Stationery Shop','Stationery','Highlighter Pen','हाइलाइटर पेन','पैक',0,1560),
(1561,'Book & Stationery Shop','Stationery','Sticky Notes','स्टिकी नोट्स','पैक',0,1561),
(1562,'Book & Stationery Shop','Stationery','Graph Notebook','ग्राफ कॉपी','पैक',0,1562),
(1563,'Mobile Store','Mobile Phones & Accessories','boAt Earbuds','बोट ईयरबड्स','पीस',0,1563),
(1564,'Mobile Store','Mobile Phones & Accessories','boAt Headphones','बोट हेडफोन','पीस',0,1564),
(1565,'Mobile Store','Mobile Phones & Accessories','boAt Bluetooth Speaker','बोट ब्लूटूथ स्पीकर','पीस',0,1565),
(1566,'Mobile Store','Mobile Phones & Accessories','Mobile OTG Adapter','मोबाइल ओटीजी अडैप्टर','पीस',0,1566),
(1567,'Mobile Store','Mobile Phones & Accessories','Mobile Stand','मोबाइल स्टैंड','पीस',0,1567),
(1568,'Mobile Store','Mobile Phones & Accessories','SIM Ejector Tool','सिम निकालने की पिन','पीस',0,1568),
(1569,'Electrical Store','Electrical Goods','Havells Ceiling Fan','हैवेल्स सीलिंग पंखा','पीस',0,1569),
(1570,'Electrical Store','Electrical Goods','Havells Modular Switch','हैवेल्स मॉड्यूलर स्विच','पीस',0,1570),
(1571,'Electrical Store','Electrical Goods','Havells MCB','हैवेल्स एमसीबी','पीस',0,1571),
(1572,'Electrical Store','Electrical Goods','Havells Electrical Wire','हैवेल्स बिजली तार','पीस',0,1572),
(1573,'Electrical Store','Electrical Goods','Fan Regulator','पंखे का रेगुलेटर','पीस',0,1573),
(1574,'Electrical Store','Electrical Goods','Plug Top','प्लग टॉप','पीस',0,1574),
(1575,'Electrical Store','Electrical Goods','Cable Tie','केबल टाई','पीस',0,1575),
(1576,'Electrical Store','Electrical Goods','Electrical Junction Box','बिजली जंक्शन बॉक्स','पीस',0,1576),
(1577,'Hardware Shop','Tools & Fasteners','Fevicol Adhesive','फेविकोल गोंद','पीस',0,1577),
(1578,'Hardware Shop','Tools & Fasteners','M-Seal Epoxy Compound','एम सील एपॉक्सी','पीस',0,1578),
(1579,'Hardware Shop','Tools & Fasteners','Allen Key Set','एलन की सेट','पीस',0,1579),
(1580,'Hardware Shop','Tools & Fasteners','Adjustable Wrench','एडजस्टेबल रिंच','पीस',0,1580),
(1581,'Hardware Shop','Tools & Fasteners','Hacksaw Frame','लोहा काटने का आरा','पीस',0,1581),
(1582,'Hardware Shop','Tools & Fasteners','Spirit Level','स्पिरिट लेवल','पीस',0,1582),
(1583,'Hardware Shop','Tools & Fasteners','Door Hinge','दरवाज़े की कब्ज़ी','पीस',0,1583),
(1584,'Hardware Shop','Tools & Fasteners','Wall Plug','वॉल प्लग रावल प्लग','पीस',0,1584),
(1585,'Kitchenware / Utensils Shop','Cookware & Utensils','Prestige Pressure Cooker','प्रेस्टीज प्रेशर कुकर','पीस',0,1585),
(1586,'Kitchenware / Utensils Shop','Cookware & Utensils','Prestige Tawa','प्रेस्टीज तवा','पीस',0,1586),
(1587,'Kitchenware / Utensils Shop','Cookware & Utensils','Prestige Frying Pan','प्रेस्टीज फ्राइंग पैन','पीस',0,1587),
(1588,'Kitchenware / Utensils Shop','Cookware & Utensils','Kitchen Strainer','रसोई की छलनी','पीस',0,1588),
(1589,'Kitchenware / Utensils Shop','Cookware & Utensils','Chopping Board','सब्जी काटने का बोर्ड','पीस',0,1589),
(1590,'Kitchenware / Utensils Shop','Cookware & Utensils','Rolling Pin Belan','बेलन','पीस',0,1590),
(1591,'Kitchenware / Utensils Shop','Cookware & Utensils','Ladle Kalchhi','कलछी','पीस',0,1591),
(1592,'Kitchenware / Utensils Shop','Cookware & Utensils','Storage Container','रसोई स्टोरेज डिब्बा','पीस',0,1592),
(1593,'Clothing / Garments Shop','Men''s Wear','Mens Cotton Kurta','पुरुषों का सूती कुर्ता','पीस',0,1593),
(1594,'Clothing / Garments Shop','Men''s Wear','Mens Vest Baniyan','पुरुषों की बनियान','पीस',0,1594),
(1595,'Clothing / Garments Shop','Men''s Wear','Mens Track Pants','पुरुषों की ट्रैक पैंट','पीस',0,1595),
(1596,'Clothing / Garments Shop','Women''s Wear','Cotton Saree','सूती साड़ी','पीस',0,1596),
(1597,'Clothing / Garments Shop','Women''s Wear','Salwar Suit Fabric','सलवार सूट कपड़ा','पीस',0,1597),
(1598,'Clothing / Garments Shop','Women''s Wear','Womens Leggings','महिलाओं की लेगिंग','पीस',0,1598),
(1599,'Clothing / Garments Shop','Women''s Wear','Dupatta','दुपट्टा','पीस',0,1599),
(1600,'Footwear Shop','Shoes & Sandals','Safety Shoes','सेफ्टी जूते','जोड़ी',0,1600),
(1601,'Footwear Shop','Shoes & Sandals','Gum Boots','रबर गम बूट','जोड़ी',0,1601),
(1602,'Footwear Shop','Shoes & Sandals','Shoe Insoles','जूते के इनसोल','जोड़ी',0,1602),
(1603,'Footwear Shop','Shoes & Sandals','Shoe Laces','जूते के फीते','जोड़ी',0,1603),
(1604,'Medical / Pharmacy','OTC & First Aid','Digital Thermometer','डिजिटल थर्मामीटर','पीस',0,1604),
(1605,'Medical / Pharmacy','OTC & First Aid','Hot Water Bag','गरम पानी की थैली','पीस',0,1605),
(1606,'Medical / Pharmacy','OTC & First Aid','Adhesive Dressing','चिपकने वाली ड्रेसिंग','पीस',0,1606),
(1607,'Medical / Pharmacy','OTC & First Aid','Elastic Crepe Bandage','इलास्टिक क्रेप बैंडेज','पीस',0,1607),
(1608,'Medical / Pharmacy','OTC & First Aid','Medical Tape','मेडिकल टेप','पीस',0,1608),
(1609,'Baby Store','Baby Products','Baby Bib','बच्चे की बिब','पीस',0,1609),
(1610,'Baby Store','Baby Products','Baby Teether','बच्चे का टीथर','पीस',0,1610),
(1611,'Baby Store','Baby Products','Baby Nail Clipper','बच्चे का नेल कटर','पीस',0,1611),
(1612,'Baby Store','Baby Products','Baby Mosquito Net','बच्चे की मच्छरदानी','पीस',0,1612),
(1613,'Pet Shop','Pet Products','Pedigree Dry Dog Food','पेडिग्री सूखा डॉग फूड','पैक',0,1613),
(1614,'Pet Shop','Pet Products','Pedigree Wet Dog Food','पेडिग्री गीला डॉग फूड','पैक',0,1614),
(1615,'Pet Shop','Pet Products','Pet Grooming Brush','पालतू पशु का ब्रश','पैक',0,1615),
(1616,'Pet Shop','Pet Products','Cat Litter','कैट लिटर','पैक',0,1616),
(1617,'Agriculture Store','Seeds & Farm Inputs','Pruning Shears','पौधे काटने की कैंची','पीस',0,1617),
(1618,'Agriculture Store','Seeds & Farm Inputs','Garden Trowel','बागवानी खुरपी','पीस',0,1618),
(1619,'Agriculture Store','Seeds & Farm Inputs','Seedling Tray','पौध तैयार करने की ट्रे','पीस',0,1619),
(1620,'Agriculture Store','Seeds & Farm Inputs','Drip Irrigation Connector','ड्रिप सिंचाई कनेक्टर','पीस',0,1620),
(1621,'Agriculture Store','Seeds & Farm Inputs','Sprayer Nozzle','स्प्रेयर नोज़ल','पीस',0,1621),
(1622,'Sanitaryware Shop','Bathroom & Plumbing','Angle Valve','एंगल वाल्व','पीस',0,1622),
(1623,'Sanitaryware Shop','Bathroom & Plumbing','PTFE Thread Seal Tape','पीटीएफई टेफ्लॉन टेप','पीस',0,1623),
(1624,'Sanitaryware Shop','Bathroom & Plumbing','Flexible Tap Connector','नल का फ्लेक्सिबल कनेक्टर','पीस',0,1624),
(1625,'Sanitaryware Shop','Bathroom & Plumbing','Flush Tank','फ्लश टंकी','पीस',0,1625),
(1626,'Sanitaryware Shop','Bathroom & Plumbing','Basin Waste Coupling','बेसिन वेस्ट कपलिंग','पीस',0,1626),
(1627,'Sports Shop','Sports Equipment','Cricket Bat Grip','क्रिकेट बैट की ग्रिप','पीस',0,1627),
(1628,'Sports Shop','Sports Equipment','Cricket Batting Gloves','क्रिकेट बैटिंग ग्लव्स','पीस',0,1628),
(1629,'Sports Shop','Sports Equipment','Cricket Batting Pads','क्रिकेट बैटिंग पैड','पीस',0,1629),
(1630,'Sports Shop','Sports Equipment','Sports Ball Pump','खेल की गेंद का पंप','पीस',0,1630),
(1631,'Sports Shop','Sports Equipment','Badminton Net','बैडमिंटन नेट','पीस',0,1631),
(1632,'Pooja Samagri Shop','Pooja Products','Mangaldeep Agarbatti','मंगलदीप अगरबत्ती','पैक',0,1632),
(1633,'Pooja Samagri Shop','Pooja Products','Cotton Diya Wicks','दीये की रूई बाती','पैक',0,1633),
(1634,'Pooja Samagri Shop','Pooja Products','Pooja Mauli Thread','पूजा मौली कलावा','पैक',0,1634),
(1635,'Pooja Samagri Shop','Pooja Products','Pooja Camphor','पूजा कपूर','पैक',0,1635),
(1636,'Pooja Samagri Shop','Pooja Products','Pooja Roli','पूजा रोली','पैक',0,1636),
(1637,'Gift & Toy Shop','Toys & Games','Building Blocks Set','बिल्डिंग ब्लॉक सेट','पीस',0,1637),
(1638,'Gift & Toy Shop','Toys & Games','Jigsaw Puzzle','जिगसॉ पहेली','पीस',0,1638),
(1639,'Gift & Toy Shop','Toys & Games','Ludo Board Game','लूडो बोर्ड गेम','पीस',0,1639),
(1640,'Gift & Toy Shop','Toys & Games','Toy Doctor Set','खिलौना डॉक्टर सेट','पीस',0,1640),
(1641,'Bicycle Shop','Bicycles','Bicycle Mudguard','साइकिल मडगार्ड','पीस',0,1641),
(1642,'Bicycle Shop','Bicycles','Bicycle Bottle Holder','साइकिल बोतल होल्डर','पीस',0,1642),
(1643,'Bicycle Shop','Bicycles','Bicycle Brake Cable','साइकिल ब्रेक केबल','पीस',0,1643),
(1644,'Bicycle Shop','Bicycles','Bicycle Saddle Cover','साइकिल सीट कवर','पीस',0,1644),
(1645,'Tyre Shop','Tyres & Wheels','Tubeless Tyre Repair Strip','ट्यूबलेस टायर रिपेयर स्ट्रिप','पीस',0,1645),
(1646,'Tyre Shop','Tyres & Wheels','Tyre Pressure Gauge','टायर हवा जाँच मीटर','पीस',0,1646),
(1647,'Tyre Shop','Tyres & Wheels','Tyre Valve Cap','टायर वाल्व कैप','पीस',0,1647),
(1648,'School Bag & Supplies Shop','School Supplies','Pencil Pouch','पेंसिल पाउच','पीस',0,1648),
(1649,'School Bag & Supplies Shop','School Supplies','Rain Cover for School Bag','स्कूल बैग का रेन कवर','पीस',0,1649),
(1650,'School Bag & Supplies Shop','School Supplies','School ID Card Holder','स्कूल आईडी कार्ड होल्डर','पीस',0,1650),
(1651,'Party Supply Store','Event Services','Paper Party Plates','पार्टी की पेपर प्लेट','पैक',0,1651),
(1652,'Party Supply Store','Event Services','Paper Party Cups','पार्टी के पेपर कप','पैक',0,1652),
(1653,'Party Supply Store','Event Services','Party Balloons','पार्टी गुब्बारे','पैक',0,1653),
(1654,'Bakery','Bread & Buns','Breadsticks','ब्रेडस्टिक्स','पैक',0,1654),
(1655,'Bakery','Bread & Buns','Hot Dog Buns','हॉट डॉग बन','पैक',0,1655),
(1656,'Sweet Shop','Traditional Sweets','Besan Laddu','बेसन लड्डू','किलो',0,1656),
(1657,'Sweet Shop','Traditional Sweets','Motichoor Laddu','मोतीचूर लड्डू','किलो',0,1657),
(1658,'Sweet Shop','Traditional Sweets','Milk Cake Sweet','मिल्क केक मिठाई','किलो',0,1658);
