-- 022: Missing essentials, brand families and searchable size/spec templates.
-- Discovery only: shopkeepers confirm pack, model, specification and own price.
-- No stock, shop offers, brand photographs or compatibility claims are inserted.
-- Brand names checked against official product families on 2026-10-08:
-- https://www.tataconsumer.com/brands/foods/tata-salt
-- https://www.fortunefoods.com/
-- https://www.parleproducts.com/
-- https://www.britannia.co.in/  https://www.maggi.in/en/our-range/
-- https://www.haldirams.com/  https://www.colgate.com/en-in/products
-- https://www.dettol.co.in/personal-hygiene/
-- https://www.in.pampers.com/diapers-wipes  https://www.huggies.co.in/diapers
SET NAMES utf8mb4;
INSERT IGNORE INTO catalog_items
(id,shop_type,sub_cat,name_en,name_hi,unit_hint,is_sewa,sort_no) VALUES
(1659,'Grocery / Kirana Store','Salt & Sugar','Sugar','चीनी शक्कर','पैक',0,1659),
(1660,'Grocery / Kirana Store','Salt & Sugar','Iodised Salt','आयोडीन युक्त नमक','पैक',0,1660),
(1661,'Grocery / Kirana Store','Salt & Sugar','Rock Salt','सेंधा नमक','पैक',0,1661),
(1662,'Grocery / Kirana Store','Salt & Sugar','Black Salt','काला नमक','पैक',0,1662),
(1663,'Grocery / Kirana Store','Salt & Sugar','Jaggery','गुड़','पैक',0,1663),
(1664,'Grocery / Kirana Store','Salt & Sugar','Jaggery Powder','गुड़ पाउडर','पैक',0,1664),
(1665,'Grocery / Kirana Store','Salt & Sugar','Mishri','मिश्री','पैक',0,1665),
(1666,'Grocery / Kirana Store','Salt & Sugar','Tata Salt','टाटा नमक','पैक',0,1666),
(1667,'Grocery / Kirana Store','Edible Oil','Fortune Soyabean Oil','फॉर्च्यून सोयाबीन तेल','पैक',0,1667),
(1668,'Grocery / Kirana Store','Edible Oil','Fortune Rice Bran Oil','फॉर्च्यून राइस ब्रान तेल','पैक',0,1668),
(1669,'Grocery / Kirana Store','Edible Oil','Fortune Mustard Oil','फॉर्च्यून सरसों तेल','पैक',0,1669),
(1670,'Grocery / Kirana Store','Atta & Flour','Fortune Wheat Atta','फॉर्च्यून गेहूँ आटा','पैक',0,1670),
(1671,'Grocery / Kirana Store','Snacks & Packaged Food','Parle-G Biscuits','पारले जी बिस्कुट','पैक',0,1671),
(1672,'Grocery / Kirana Store','Snacks & Packaged Food','Parle Monaco Biscuits','पारले मोनाको बिस्कुट','पैक',0,1672),
(1673,'Grocery / Kirana Store','Snacks & Packaged Food','Parle KrackJack Biscuits','पारले क्रैकजैक बिस्कुट','पैक',0,1673),
(1674,'Grocery / Kirana Store','Snacks & Packaged Food','Parle Hide & Seek Cookies','पारले हाइड एंड सीक कुकीज़','पैक',0,1674),
(1675,'Grocery / Kirana Store','Snacks & Packaged Food','Britannia Biscuits','ब्रिटानिया बिस्कुट','पैक',0,1675),
(1676,'Grocery / Kirana Store','Snacks & Packaged Food','Britannia Good Day Cookies','ब्रिटानिया गुड डे कुकीज़','पैक',0,1676),
(1677,'Grocery / Kirana Store','Snacks & Packaged Food','Britannia Rusk','ब्रिटानिया रस्क','पैक',0,1677),
(1678,'Grocery / Kirana Store','Snacks & Packaged Food','Maggi Noodles','मैगी नूडल्स','पैक',0,1678),
(1679,'Grocery / Kirana Store','Snacks & Packaged Food','Haldiram Bhujia Sev','हल्दीराम भुजिया सेव','पैक',0,1679),
(1680,'Grocery / Kirana Store','Snacks & Packaged Food','Haldiram Aloo Bhujia','हल्दीराम आलू भुजिया','पैक',0,1680),
(1681,'Grocery / Kirana Store','Snacks & Packaged Food','Soya Chunks','सोया चंक्स बड़ी','पैक',0,1681),
(1682,'Grocery / Kirana Store','Snacks & Packaged Food','Tomato Ketchup','टमाटर केचप','पैक',0,1682),
(1683,'Grocery / Kirana Store','Snacks & Packaged Food','Soy Sauce','सोया सॉस','पैक',0,1683),
(1684,'Grocery / Kirana Store','Snacks & Packaged Food','Chilli Sauce','चिली सॉस','पैक',0,1684),
(1685,'Grocery / Kirana Store','Snacks & Packaged Food','Vinegar','सिरका','पैक',0,1685),
(1686,'Grocery / Kirana Store','Snacks & Packaged Food','Baking Soda','खाने का सोडा','पैक',0,1686),
(1687,'Grocery / Kirana Store','Snacks & Packaged Food','Baking Powder','बेकिंग पाउडर','पैक',0,1687),
(1688,'Grocery / Kirana Store','Snacks & Packaged Food','Custard Powder','कस्टर्ड पाउडर','पैक',0,1688),
(1689,'Grocery / Kirana Store','Snacks & Packaged Food','Corn Starch','कॉर्न स्टार्च','पैक',0,1689),
(1690,'Grocery / Kirana Store','Snacks & Packaged Food','Instant Soup','इंस्टेंट सूप','पैक',0,1690),
(1691,'Grocery / Kirana Store','Snacks & Packaged Food','Pickle','अचार','पैक',0,1691),
(1692,'Grocery / Kirana Store','Spices','Mustard Seeds','राई सरसों दाना','पैक',0,1692),
(1693,'Grocery / Kirana Store','Spices','Fenugreek Seeds','मेथी दाना','पैक',0,1693),
(1694,'Grocery / Kirana Store','Spices','Fennel Seeds','सौंफ','पैक',0,1694),
(1695,'Grocery / Kirana Store','Spices','Ajwain','अजवाइन','पैक',0,1695),
(1696,'Grocery / Kirana Store','Spices','Asafoetida','हींग','पैक',0,1696),
(1697,'Grocery / Kirana Store','Spices','Bay Leaves','तेज पत्ता','पैक',0,1697),
(1698,'Grocery / Kirana Store','Spices','Kasuri Methi','कसूरी मेथी','पैक',0,1698),
(1699,'Grocery / Kirana Store','Spices','Dry Mango Powder','अमचूर पाउडर','पैक',0,1699),
(1700,'Cosmetics & Beauty Store','Oral Care','Colgate Toothpaste','कोलगेट टूथपेस्ट','पैक',0,1700),
(1701,'Cosmetics & Beauty Store','Oral Care','Colgate MaxFresh Toothpaste','कोलगेट मैक्सफ्रेश टूथपेस्ट','पैक',0,1701),
(1702,'Cosmetics & Beauty Store','Oral Care','Colgate Total Toothpaste','कोलगेट टोटल टूथपेस्ट','पैक',0,1702),
(1703,'Cosmetics & Beauty Store','Oral Care','Colgate Toothbrush','कोलगेट टूथब्रश','पैक',0,1703),
(1704,'Cosmetics & Beauty Store','Oral Care','Colgate Plax Mouthwash','कोलगेट प्लैक्स माउथवॉश','पैक',0,1704),
(1705,'Cosmetics & Beauty Store','Oral Care','Dental Floss','डेंटल फ्लॉस','पैक',0,1705),
(1706,'Cosmetics & Beauty Store','Oral Care','Tongue Cleaner','जीभ साफ करने वाला','पैक',0,1706),
(1707,'Cosmetics & Beauty Store','Skin Care','Dettol Original Soap','डेटॉल ओरिजिनल साबुन','पैक',0,1707),
(1708,'Cosmetics & Beauty Store','Skin Care','Dettol Liquid Handwash','डेटॉल लिक्विड हैंडवॉश','पैक',0,1708),
(1709,'Cosmetics & Beauty Store','Skin Care','Dettol Hand Sanitizer','डेटॉल हैंड सैनिटाइज़र','पैक',0,1709),
(1710,'Cosmetics & Beauty Store','Skin Care','Sanitary Pads','सैनिटरी पैड','पैक',0,1710),
(1711,'Cosmetics & Beauty Store','Skin Care','Cotton Buds','कॉटन बड्स','पैक',0,1711),
(1712,'Baby Store','Baby Products','Pampers Diaper Pants','पैम्पर्स डायपर पैंट','पैक',0,1712),
(1713,'Baby Store','Baby Products','Pampers Newborn Diapers','पैम्पर्स नवजात डायपर','पैक',0,1713),
(1714,'Baby Store','Baby Products','Pampers Baby Wipes','पैम्पर्स बेबी वाइप्स','पैक',0,1714),
(1715,'Baby Store','Baby Products','Huggies Natural Soft Pants','हगीज़ नैचुरल सॉफ्ट पैंट','पैक',0,1715),
(1716,'Baby Store','Baby Products','Huggies Newborn Taped Diapers','हगीज़ नवजात टेप डायपर','पैक',0,1716),
(1717,'Baby Store','Baby Products','Huggies Baby Wipes','हगीज़ बेबी वाइप्स','पैक',0,1717),
(1718,'Baby Store','Baby Products','Reusable Cloth Diaper','दोबारा उपयोग वाला कपड़े का डायपर','पैक',0,1718),
(1719,'Baby Store','Baby Products','Baby Feeding Spoon','बच्चे का फीडिंग चम्मच','पैक',0,1719),
(1720,'Baby Store','Baby Products','Baby Sipper Cup','बच्चे का सिपर कप','पैक',0,1720),
(1721,'Mobile Store','Mobile Phones & Accessories','Samsung Phone Cover','सैमसंग फोन कवर','पीस',0,1721),
(1722,'Mobile Store','Mobile Phones & Accessories','Samsung Phone Tempered Glass','सैमसंग फोन टेम्पर्ड ग्लास','पीस',0,1722),
(1723,'Mobile Store','Mobile Phones & Accessories','Redmi Phone Cover','रेडमी फोन कवर','पीस',0,1723),
(1724,'Mobile Store','Mobile Phones & Accessories','Redmi Phone Tempered Glass','रेडमी फोन टेम्पर्ड ग्लास','पीस',0,1724),
(1725,'Mobile Store','Mobile Phones & Accessories','iPhone Cover','आईफोन कवर','पीस',0,1725),
(1726,'Mobile Store','Mobile Phones & Accessories','iPhone Tempered Glass','आईफोन टेम्पर्ड ग्लास','पीस',0,1726),
(1727,'Mobile Store','Mobile Phones & Accessories','Lightning Cable','लाइटनिंग केबल','पीस',0,1727),
(1728,'Mobile Store','Mobile Phones & Accessories','USB-C to USB-C Cable','यूएसबी सी से यूएसबी सी केबल','पीस',0,1728),
(1729,'Mobile Store','Mobile Phones & Accessories','Micro USB Cable','माइक्रो यूएसबी केबल','पीस',0,1729),
(1730,'Mobile Store','Mobile Phones & Accessories','Car Phone Charger','कार फोन चार्जर','पीस',0,1730),
(1731,'Mobile Store','Mobile Phones & Accessories','Phone Camera Lens Protector','फोन कैमरा लेंस प्रोटेक्टर','पीस',0,1731),
(1732,'Clothing / Garments Shop','Men''s Wear','Men Cotton T-Shirt','पुरुषों की कॉटन टीशर्ट','पीस',0,1732),
(1733,'Clothing / Garments Shop','Men''s Wear','Men Linen Shirt','पुरुषों की लिनेन शर्ट','पीस',0,1733),
(1734,'Clothing / Garments Shop','Men''s Wear','Men Thermal Wear','पुरुषों के थर्मल कपड़े','पीस',0,1734),
(1735,'Clothing / Garments Shop','Men''s Wear','Men Cotton Pyjama','पुरुषों का कॉटन पायजामा','पीस',0,1735),
(1736,'Clothing / Garments Shop','Women''s Wear','Women Cotton Nighty','महिलाओं की कॉटन नाइटी','पीस',0,1736),
(1737,'Clothing / Garments Shop','Women''s Wear','Women Cotton Kurti','महिलाओं की कॉटन कुर्ती','पीस',0,1737),
(1738,'Clothing / Garments Shop','Women''s Wear','Women Thermal Wear','महिलाओं के थर्मल कपड़े','पीस',0,1738),
(1739,'Clothing / Garments Shop','Women''s Wear','Women Cotton Petticoat','महिलाओं का कॉटन पेटीकोट','पीस',0,1739),
(1740,'Clothing / Garments Shop','Kids Wear','Kids Cotton Night Suit','बच्चों का कॉटन नाइट सूट','पीस',0,1740),
(1741,'Clothing / Garments Shop','Kids Wear','Kids Thermal Wear','बच्चों के थर्मल कपड़े','पीस',0,1741),
(1742,'Footwear Shop','Shoes & Sandals','Women Ballerina Flats','महिलाओं के बैलेरीना फ्लैट जूते','जोड़ी',0,1742),
(1743,'Footwear Shop','Shoes & Sandals','Women Heeled Sandals','महिलाओं की हील वाली सैंडल','जोड़ी',0,1743),
(1744,'Footwear Shop','Shoes & Sandals','Men Leather Formal Shoes','पुरुषों के लेदर फॉर्मल जूते','जोड़ी',0,1744),
(1745,'Footwear Shop','Shoes & Sandals','Kids Velcro Shoes','बच्चों के वेल्क्रो जूते','जोड़ी',0,1745),
(1746,'Electrical Store','Electrical Goods','LED Bulb 5W','एलईडी बल्ब 5 वाट','पीस',0,1746),
(1747,'Electrical Store','Electrical Goods','LED Bulb 9W','एलईडी बल्ब 9 वाट','पीस',0,1747),
(1748,'Electrical Store','Electrical Goods','LED Bulb 12W','एलईडी बल्ब 12 वाट','पीस',0,1748),
(1749,'Electrical Store','Electrical Goods','LED Bulb 15W','एलईडी बल्ब 15 वाट','पीस',0,1749),
(1750,'Electrical Store','Electrical Goods','LED Bulb 20W','एलईडी बल्ब 20 वाट','पीस',0,1750),
(1751,'Electrical Store','Electrical Goods','Copper Wire 1.5 sq mm','कॉपर वायर 1.5 वर्ग मिमी','मीटर',0,1751),
(1752,'Electrical Store','Electrical Goods','Copper Wire 2.5 sq mm','कॉपर वायर 2.5 वर्ग मिमी','मीटर',0,1752),
(1753,'Electrical Store','Electrical Goods','Copper Wire 4 sq mm','कॉपर वायर 4 वर्ग मिमी','मीटर',0,1753),
(1754,'Electrical Store','Electrical Goods','Copper Wire 6 sq mm','कॉपर वायर 6 वर्ग मिमी','मीटर',0,1754),
(1755,'Electrical Store','Electrical Goods','LED Strip Light','एलईडी स्ट्रिप लाइट','पीस',0,1755),
(1756,'Electrical Store','Electrical Goods','Emergency Rechargeable Light','चार्ज होने वाली इमरजेंसी लाइट','पीस',0,1756),
(1757,'Hardware Shop','Tools & Fasteners','Screwdriver Bit Set','पेचकस बिट सेट','पीस',0,1757),
(1758,'Hardware Shop','Tools & Fasteners','Safety Goggles','सुरक्षा चश्मा','पीस',0,1758),
(1759,'Hardware Shop','Tools & Fasteners','Work Gloves','काम के सुरक्षा दस्ताने','पीस',0,1759),
(1760,'Hardware Shop','Tools & Fasteners','Sandpaper','सैंडपेपर रेगमाल','पीस',0,1760),
(1761,'Hardware Shop','Tools & Fasteners','Utility Knife','यूटिलिटी कटर','पीस',0,1761),
(1762,'Hardware Shop','Tools & Fasteners','Silicone Sealant','सिलिकॉन सीलेंट','पीस',0,1762),
(1763,'Plumbing Store','Plumbing','PVC Pipe 20 mm','पीवीसी पाइप 20 मिमी','पीस',0,1763),
(1764,'Plumbing Store','Plumbing','PVC Pipe 25 mm','पीवीसी पाइप 25 मिमी','पीस',0,1764),
(1765,'Plumbing Store','Plumbing','PVC Pipe 32 mm','पीवीसी पाइप 32 मिमी','पीस',0,1765),
(1766,'Plumbing Store','Plumbing','CPVC Pipe 20 mm','सीपीवीसी पाइप 20 मिमी','पीस',0,1766),
(1767,'Plumbing Store','Plumbing','CPVC Pipe 25 mm','सीपीवीसी पाइप 25 मिमी','पीस',0,1767),
(1768,'Plumbing Store','Plumbing','Pipe Reducer','पाइप रिड्यूसर','पीस',0,1768),
(1769,'Plumbing Store','Plumbing','Pipe Union','पाइप यूनियन','पीस',0,1769),
(1770,'Plumbing Store','Plumbing','Pipe End Cap','पाइप एंड कैप','पीस',0,1770),
(1771,'Plumbing Store','Plumbing','PVC Solvent Cement','पीवीसी सॉल्वेंट सीमेंट','पीस',0,1771),
(1772,'Agriculture Store','Seeds & Farm Inputs','Urea Fertilizer','यूरिया खाद','पैक',0,1772),
(1773,'Agriculture Store','Seeds & Farm Inputs','DAP Fertilizer','डीएपी खाद','पैक',0,1773),
(1774,'Agriculture Store','Seeds & Farm Inputs','NPK Fertilizer','एनपीके खाद','पैक',0,1774),
(1775,'Agriculture Store','Seeds & Farm Inputs','Vermicompost','वर्मी कम्पोस्ट','पैक',0,1775),
(1776,'Agriculture Store','Seeds & Farm Inputs','Neem Cake','नीम खली','पैक',0,1776),
(1777,'Agriculture Store','Seeds & Farm Inputs','Tomato Seeds','टमाटर बीज','पैक',0,1777),
(1778,'Agriculture Store','Seeds & Farm Inputs','Okra Seeds','भिंडी बीज','पैक',0,1778),
(1779,'Agriculture Store','Seeds & Farm Inputs','Onion Seeds','प्याज बीज','पैक',0,1779),
(1780,'Agriculture Store','Seeds & Farm Inputs','Brinjal Seeds','बैंगन बीज','पैक',0,1780),
(1781,'Agriculture Store','Seeds & Farm Inputs','Chilli Seeds','मिर्च बीज','पैक',0,1781),
(1782,'Agriculture Store','Seeds & Farm Inputs','Coriander Seeds for Sowing','बोने के लिए धनिया बीज','पैक',0,1782),
(1783,'Agriculture Store','Seeds & Farm Inputs','Cucumber Seeds','खीरा बीज','पैक',0,1783),
(1784,'Agriculture Store','Seeds & Farm Inputs','Bottle Gourd Seeds','लौकी बीज','पैक',0,1784),
(1785,'Agriculture Store','Seeds & Farm Inputs','Pea Seeds','मटर बीज','पैक',0,1785),
(1786,'Auto Spare Parts Shop','Bike & Car Parts','Bike Chain Sprocket Kit','बाइक चेन स्प्रोकेट किट','पीस',0,1786),
(1787,'Auto Spare Parts Shop','Bike & Car Parts','Vehicle Indicator Lamp','गाड़ी की इंडिकेटर लाइट','पीस',0,1787),
(1788,'Auto Spare Parts Shop','Bike & Car Parts','Wiper Blade','वाइपर ब्लेड','पीस',0,1788),
(1789,'Auto Spare Parts Shop','Bike & Car Parts','Wheel Bearing','पहिए का बेयरिंग','पीस',0,1789),
(1790,'Auto Spare Parts Shop','Bike & Car Parts','Brake Shoe','ब्रेक शू','पीस',0,1790),
(1791,'Auto Spare Parts Shop','Bike & Car Parts','Accelerator Cable','एक्सीलेरेटर केबल','पीस',0,1791),
(1792,'Auto Spare Parts Shop','Bike & Car Parts','Fuel Filter','फ्यूल फिल्टर','पीस',0,1792),
(1793,'Auto Spare Parts Shop','Bike & Car Parts','Vehicle Horn','गाड़ी का हॉर्न','पीस',0,1793),
(1794,'Auto Spare Parts Shop','Bike & Car Parts','Vehicle Fuse','गाड़ी का फ्यूज़','पीस',0,1794);
